services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  #    volumes:
  #      - rabbitmq_data:/var/lib/rabbitmq

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  production-db:
    image: mariadb:11
    container_name: production-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: production_service_db
#    ports:
#      - "3307:3306"

  production-service:
    build:
      context: ./production-service
      dockerfile: Dockerfile
    restart: always
    container_name: production_service
    depends_on:
      - production-db
      - eureka-server
    environment:
      DB_URL: jdbc:mariadb://production-db:3306/production_service_db
      DB_USERNAME: root
      DB_PASSWORD: 12345
      INVENTORY_BASE_URL: http://inventory-service:8082
    ports:
      - "8081:8081"

  inventory-db:
    image: mariadb:11
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: inventory_service_db

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    depends_on:
      - inventory-db
      - eureka-server
    environment:
      DB_URL: jdbc:mariadb://inventory-db:3306/inventory_service_db
      DB_USERNAME: root
      DB_PASSWORD: 12345
      PRODUCTION_BASE_URL: http://production-service:8081
    ports:
      - "8082:8082"
#  sales-service:
#    build: ./sales-service
#    depends_on:
#      - eureka-server