services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  #    volumes:
  #      - rabbitmq_data:/var/lib/rabbitmq

  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  production-db:
    image: mariadb:11
    container_name: production-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: production_service_db
#    ports:
#      - "3307:3306"

  production-service:
    build:
      context: ./production-service
      dockerfile: Dockerfile
    restart: always
    container_name: production_service
    depends_on:
      - production-db
      - eureka-service
    environment:
      DB_URL: jdbc:mariadb://production-db:3306/production_service_db
      DB_USERNAME: root
      DB_PASSWORD: 12345
      INVENTORY_BASE_URL: http://inventory-service:8082
    ports:
      - "8081:8081"

#  inventory-service:
#    build: ./inventory-service
#    depends_on:
#      - eureka-service
#  sales-service:
#    build: ./sales-service
#    depends_on:
#      - eureka-service