server:
  port: 8085

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: my-secret-key-which-should-be-veeeeeeery-long

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: production-service
              uri: http://production-service:8081
              predicates:
                - Path=/production/v1/**

            - id: inventory-service
              uri: http://inventory-service:8082
              predicates:
                - Path=/inventory/v1/**

            - id: sales-service
              uri: http://sales-service:8083
              predicates:
                - Path=/sales/v1/**

services:
  inventory:
    base-url: http://inventory-service:8082
  sales:
    base-url: http://sales-service:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9:
#  eyJzdWIiOiIxMjMiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE3MTAwMDAwMDAsImV4cCI6MTkxMDAwMDAwMH0:
#    A4v9XGqOB5wXEyIzkwfQu22QVm4hIj-ZLkXFlwSg0KI: