spring:
  application:
    name: production-service

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
    url: ${DB_URL:jdbc:mariadb://localhost:3306/production_service_db}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: ${OPENAPI_PATH:/v3/api-docs}   # шлях до JSON документації OpenAPI
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}  # шлях до Swagger UI
    operationsSorter: alpha # сортування операцій в UI
    tagsSorter: alpha       # сортування тегів

server:
  port: ${SERVER_PORT:8081}

inventory-service:
  base-url: ${INVENTORY_BASE_URL:http://localhost:8082}
  inventory-path: ${INVENTORY_BASE_URL:http://localhost:8082}