spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: production-service
              uri: ${services.production.base-url}
              predicates:
                - Path=/production/v1/**

            - id: inventory-service
              uri: ${services.inventory.base-url}
              predicates:
                - Path=/inventory/v1/**

            - id: sales-service
              uri: ${services.sales.base-url}
              predicates:
                - Path=/sales/v1/**

#services:
#  inventory:
#    base-url: http://inventory-service:8082
#  sales:
#    base-url: http://sales-service:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka