spring:
  application:
    name: inventory-service

  datasource:
    username: root
    password: 12345
    url: jdbc:mariadb://localhost:3306/inventory_service_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

production-service:
    base-url: http://localhost:8082
    production-path: /production/v1