spring:
  application:
    name: inventory-service

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_USERNAME:12345}
    url: ${DB_URL:jdbc:mariadb://localhost:3306/inventory_service_db}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8082}

production-service:
    base-url: ${PRODUCTION_BASE_URL:http://localhost:8081}
    production-path: ${PRODUCTION_BASE_URL:http://localhost:8081}