server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672

  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/production_service_db

  flyway:
    url: jdbc:mariadb://localhost:3306/production_service_db
    user: root
    password: 12345

inventory-service:
  base-url: http://localhost:8082
  inventory-path: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka