server:
  port: ${SERVER_PORT:8081}

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
  #    username: ${RABBIT_USERNAME}
  #    password: ${RABBIT_PASSWORD}

  datasource:
    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    url: ${DB_URL:jdbc:mariadb://production-db:3306/production_service_db}

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

inventory-service:
  base-url: ${INVENTORY_BASE_URL:http://inventory-service:8082}
  inventory-path: ${INVENTORY_BASE_URL:http://inventory-service:8082}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka